name = "Jl"
uuid = "d94132cf-1b75-44f1-93bc-b683902657ec"
version = "0.1.0"
authors = ["Martijn Visser <mgvisser@gmail.com>"]

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Pkg = "1"
julia = "1.12"

[workspace]
projects = ["test"]

[apps.jl]
